package com.tsd.enums;

public enum ConfigProperties {
   URL,
   BROWSER,
   OVERRIDEREPORTS,
   PASSEDSTEPSSCREENSHOTS,
   FAILEDSTEPSSCREENSHOTS,
   SKIPPEDSTEPSSCREENSHOTS,
   RETRYFAILEDTESTS,
   RUNMODE
}
